<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akomodasi-lainnya</name>
   <tag></tag>
   <elementGuidId>82c85631-bb44-4171-8070-2e0acc6990bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='IT Risk Management']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ff4e481a-20d4-4612-937d-d848e9d84d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709138135466</value>
      <webElementGuid>d6d249e1-9eed-4bb3-b38e-d132e9a237fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
