<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BUS</name>
   <tag></tag>
   <elementGuidId>489716a1-385b-46fe-b3cf-54ac8e3e69e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Bus/travel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b253e8aa-558b-46fb-996a-cb44a15fe408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015468181</value>
      <webElementGuid>1eb9d336-10fd-49b1-90a3-f6163dc7f67d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
