<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calculate</name>
   <tag></tag>
   <elementGuidId>e7c244e5-7445-4545-9f74-a09fa2107990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='main_lbcalculate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>fce61e57-8ee1-4fd9-b7fc-40dd56cf650f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709009239362</value>
      <webElementGuid>763b8351-1bc1-499b-8e53-0e6b3b126041</webElementGuid>
   </webElementProperties>
</WebElementEntity>
