<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COP-MOP</name>
   <tag></tag>
   <elementGuidId>9775130c-9c0e-4056-a851-44b86bd8162f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Kendaraan COP/ MOP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a744e22c-ca9a-4b56-8666-11ae434d8903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015468851</value>
      <webElementGuid>b7ee4612-5db3-47da-9640-607f0fdb70f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
