<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DalamKota</name>
   <tag></tag>
   <elementGuidId>49919c97-e27a-4db0-9bcd-28c9fd03da3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Dalam Kota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>61bf4445-5269-4ac0-a350-07cd7ab9856c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709009729246</value>
      <webElementGuid>8b3500d8-5413-4961-ae93-020df5e6af4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
