<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Hotel</name>
   <tag></tag>
   <elementGuidId>9905c56f-4a9b-4414-b4d5-fcb913e21d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Hotel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>72147f14-fdea-4a5b-9edb-4a62173cd21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015469678</value>
      <webElementGuid>ddb17aa1-379d-4cf9-9ae5-543eb643fd30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
