<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Kembali</name>
   <tag></tag>
   <elementGuidId>6381c311-1387-4777-a64f-12a6b99be80e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txttglkembali</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttglkembali']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da5298a0-e157-4c46-9c1d-86db6d41b0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttglkembali</value>
      <webElementGuid>a8303d63-f9e2-43cf-b4ff-2ed1b5408e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef39b3ec-1fd8-4145-9cef-9e2b313856f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$txttglkembali\',\'\')', 0)</value>
      <webElementGuid>71fe6476-0663-4301-986e-9d10b473740e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>95f14958-23c9-4306-bb64-8416f982107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttglkembali</value>
      <webElementGuid>464f0d01-d896-4565-bbc0-99c87af9d360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>82a8d753-b825-4932-a4be-e00a3a8a4c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#datepicker</value>
      <webElementGuid>e046588e-9797-4843-8541-1ff34d592a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttglkembali&quot;)</value>
      <webElementGuid>965f5635-4544-4d51-939a-9ac38aa79a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttglkembali']</value>
      <webElementGuid>5b8dae33-1f7b-4e3a-a842-998be6c5fa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[7]/div/div/input</value>
      <webElementGuid>e111f4a7-c6c0-4aa7-956a-5ac00e49bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>ded2c30f-9da5-4b51-84ae-9206f1d5bdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttglkembali' and @type = 'text' and @id = 'main_txttglkembali']</value>
      <webElementGuid>c1cec5f6-bc77-4008-b1e4-c6802b47d526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
