<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jam Berangkat</name>
   <tag></tag>
   <elementGuidId>e6ab2b19-4318-4087-ba6a-1857d320ec00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txtjamawal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txtjamawal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cae1991a-74c5-4ec2-b6b8-e7ea7746c0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txtjamawal</value>
      <webElementGuid>7285f168-356d-4f8b-89be-cb4c882adc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17a5b69d-b84e-42c8-bc18-bcb31cf7df6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>00f61cb1-2814-4e73-be0a-c66200af2b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>48473c8a-44f0-4d5c-8d30-6071b91e0e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$txtjamawal\',\'\')', 0)</value>
      <webElementGuid>ceb7a954-392f-4a34-9444-ac790b8dff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return isnumerickey(event);</value>
      <webElementGuid>b4fb264f-24e9-48f8-bdca-93e74efb25f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txtjamawal</value>
      <webElementGuid>dbc6adc4-09ea-43af-bd3a-0504dfff1610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control timepicker</value>
      <webElementGuid>eeb32575-a564-4ca1-8fd0-2806e508210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH:MM:SS</value>
      <webElementGuid>f1a2f481-375d-48fc-a1b3-af355f3024e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txtjamawal&quot;)</value>
      <webElementGuid>757deb2d-913f-4ea2-ac5a-cb69616794b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txtjamawal']</value>
      <webElementGuid>76099a24-e8e6-4dea-b187-25dd8e117461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[6]/div[2]/div/input</value>
      <webElementGuid>444b5bfa-7d76-4a64-a47e-2ec77fa46639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/input</value>
      <webElementGuid>7f470c55-9582-4148-b02f-1d7fd4715300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txtjamawal' and @type = 'text' and @id = 'main_txtjamawal' and @placeholder = 'HH:MM:SS']</value>
      <webElementGuid>5cce65a5-022c-433f-ae0a-0783ab6677a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
