<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tujuan Rekening Cash Advace</name>
   <tag></tag>
   <elementGuidId>c9d4bdaf-e0db-4fde-984e-35a9d05e7f8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txttujuanrekcas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttujuanrekcas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce98f51b-892e-483d-a1c7-54207bb50b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttujuanrekcas</value>
      <webElementGuid>4a933c7a-d11a-4a56-b6b7-9cf3f1ffea75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a635af3-554b-4021-81d3-719dc90c229b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttujuanrekcas</value>
      <webElementGuid>56d8763e-fbdb-4e1d-818f-b73ac6244b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de0f62fa-1950-4dcd-8665-0bbd3eeff649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttujuanrekcas&quot;)</value>
      <webElementGuid>76499f54-b2d6-4057-963f-77c29e33aae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttujuanrekcas']</value>
      <webElementGuid>a8457ee7-4bab-43b3-b79f-2806a2ccc15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[9]/div[3]/div/input</value>
      <webElementGuid>39b6248a-c7c4-4774-8559-d229a0ff44a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/div/input</value>
      <webElementGuid>f9370b18-6fc7-4115-90d7-4867cf61b6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttujuanrekcas' and @type = 'text' and @id = 'main_txttujuanrekcas']</value>
      <webElementGuid>0ed047ab-18e4-44d5-be8b-7d22e4bfbdfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
