<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tujuan</name>
   <tag></tag>
   <elementGuidId>63ed503b-9607-4456-9d7e-c0d83e2a9533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_txttujuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_txttujuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>539f382a-d34e-4026-9465-8512bde6f1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$txttujuan</value>
      <webElementGuid>d092a489-0f18-473b-b534-d570e9d209e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbe03f23-4c15-40c1-a73f-86c8de3e434d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_txttujuan</value>
      <webElementGuid>ec9283c4-3b78-4cb7-be1f-892deafaa8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffb31ebc-7aea-4fd2-b1d2-4b9fd356b3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_txttujuan&quot;)</value>
      <webElementGuid>3957fb6e-18f1-4b9f-ab24-faf0b5c13fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_txttujuan']</value>
      <webElementGuid>f88443ce-3ff6-459f-aa11-c7cce6dccc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[9]/div/div/input</value>
      <webElementGuid>0689f636-cb77-43fe-97ca-0a4fdad62b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>44d223e1-1259-41fd-8ff2-583f90be6819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$main$txttujuan' and @type = 'text' and @id = 'main_txttujuan']</value>
      <webElementGuid>e949ed89-320a-4c15-a8bd-959251bdb16b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
