<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KendaraanOperasional</name>
   <tag></tag>
   <elementGuidId>7f8119cf-cbf2-4d66-9046-75b89bf59b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Kendaraan Operasional']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5af6a1c9-d966-4127-9870-00120595e0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015468539</value>
      <webElementGuid>da57a1d1-8ab6-4d01-8396-836067d625ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
