<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keperluan-Seminar</name>
   <tag></tag>
   <elementGuidId>d52a8bec-8367-46bc-83e7-b37dad26b459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Seminar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0a500a89-6cdd-4fe0-8933-8510ef6940f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709009842350</value>
      <webElementGuid>8740e788-b6f8-49a1-a39a-7fac31fc05b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
