<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keperluan-Meeting</name>
   <tag></tag>
   <elementGuidId>162aa2c9-fc45-4e13-9e50-3b7a2ceab84b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Meeting']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>52f507e1-05b7-4e32-b7de-32413f1df62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709009787730</value>
      <webElementGuid>91298ee9-eac1-4a03-9fa7-55bdf59c3246</webElementGuid>
   </webElementProperties>
</WebElementEntity>
