<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keperluan-Training</name>
   <tag></tag>
   <elementGuidId>21e9d9df-7326-4bd4-9c6c-247caffa1da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Training']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a6e6c1c4-ca54-4f27-9cb1-889ab36c1de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709009866793</value>
      <webElementGuid>23bf037a-6bed-4ada-860b-fd71955294d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
