<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Laki-Laki</name>
   <tag></tag>
   <elementGuidId>ab3245ff-8f6f-43ab-bbb7-7257bac73789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Laki-laki']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9b101a64-1433-401b-9af4-5f2131813161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015470981</value>
      <webElementGuid>9e6631c3-2ea5-4bcb-9cec-017d26f8b4a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
