<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Makassar</name>
   <tag></tag>
   <elementGuidId>886b92d3-b597-46f2-a88a-fc8d3b92a18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='MAKASSAR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>41d93cd6-8094-4a4e-a4eb-4de0dd20234a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015470754</value>
      <webElementGuid>9bc232f9-6c40-4c4e-8583-3ce69dd8f287</webElementGuid>
   </webElementProperties>
</WebElementEntity>
