<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Perempuan</name>
   <tag></tag>
   <elementGuidId>31370305-bcee-4b25-8afa-b87fcd4cf393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Perempuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>912e4f4f-f5ba-40b6-858f-c83c2eaa1291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709016028671</value>
      <webElementGuid>a133cab8-a0d1-48b2-8d07-f3041e86d3e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
