<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rental</name>
   <tag></tag>
   <elementGuidId>91cee382-adb1-4390-a4eb-9f753badacec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Kendaraan Rental']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>26c469ca-d2f7-4de8-b9e1-0c9fe818f5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709015469109</value>
      <webElementGuid>36e7d531-55f4-4def-82ee-c167405a13ad</webElementGuid>
   </webElementProperties>
</WebElementEntity>
