<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtusername</name>
   <tag></tag>
   <elementGuidId>dcadf92b-fe9b-4b57-bd49-01edd4d822ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtusername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtusername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1869d782-9a18-4168-bfd4-3721da9693c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtusername</value>
      <webElementGuid>37ec2a45-c1a1-4411-b3f8-85d7ff295e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cf82e73-2fbe-4f8e-9a0c-f35a64b5ecf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtusername</value>
      <webElementGuid>09ea329f-1cde-4b73-8309-61445c4a4fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3f96328-cc1a-4089-8c10-92b3e6621ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input NRK</value>
      <webElementGuid>7f7847f4-ee52-4f6e-ba99-8308c9e83640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtusername&quot;)</value>
      <webElementGuid>18e31494-331b-4c2d-8cbf-8fd5c29c9e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtusername']</value>
      <webElementGuid>3efbeed5-33ff-4a8d-bfd9-cfbee4c2ee33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>1b986cf6-3017-417e-bab0-8c8bf144e42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f75595a6-6262-48c3-bde9-675156d1f131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtusername' and @type = 'text' and @id = 'txtusername' and @placeholder = 'Input NRK']</value>
      <webElementGuid>bbc3d8d4-1f15-4d3c-8a5d-c6cfae918a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
