<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Master Biaya</name>
   <tag></tag>
   <elementGuidId>d6999355-3452-49f8-9981-3f356e4f3210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdf739b9-b42f-4dfb-aff7-1cf6cc10951f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>a266190b-c86e-4e37-a9fc-1b969b3c2e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/PerjalananDinas/MasterBiaya.aspx</value>
      <webElementGuid>36afb9df-ede8-4163-9c59-e7509db6d770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t0</value>
      <webElementGuid>3b35ede3-e26a-41e6-8f66-c80c7f6de542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Biaya</value>
      <webElementGuid>ac49a98c-032d-4772-ae84-64316377a6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t0&quot;)</value>
      <webElementGuid>35099917-871d-4de5-8c1d-694f59b83d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t0']</value>
      <webElementGuid>dbfbc865-96e7-427e-9a38-aa89aed8aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>17a178c8-8fed-4e9f-a283-23ae3e3dc201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Master Biaya')]</value>
      <webElementGuid>4e49bb26-49f9-4bb1-8a18-be6355e4ddca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links.'])[1]/following::a[1]</value>
      <webElementGuid>e9ea6c0f-8c33-4664-a644-4e996267fc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Perdin'])[1]/preceding::a[2]</value>
      <webElementGuid>d632608a-f91e-4083-8de5-e3ae858adc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan'])[1]/preceding::a[3]</value>
      <webElementGuid>6060ae98-5547-4705-9d31-59b7846e71ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master Biaya']/parent::*</value>
      <webElementGuid>215ddf73-bc34-4454-8092-83b956f16eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/PerjalananDinas/MasterBiaya.aspx')]</value>
      <webElementGuid>db7bca9a-ff2e-4e5f-b8a6-e25ec876800c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>1cc14011-16ec-4aaa-918d-276bc465b6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/PerjalananDinas/MasterBiaya.aspx' and @id = 'TreeView1t0' and (text() = 'Master Biaya' or . = 'Master Biaya')]</value>
      <webElementGuid>39f796e1-a10d-4a97-97ea-3347cc24f5b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
