<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akomodasi_Hotelpermalam</name>
   <tag></tag>
   <elementGuidId>a917211e-0d48-4b79-af6c-3ae4a4e47604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-main_ddlakomodasi-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-main_ddlakomodasi-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2abef28a-e78e-4bb1-9506-63965b39edec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>30442ae4-310a-4e77-bf0e-ff76d554696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-main_ddlakomodasi-container</value>
      <webElementGuid>e245037e-2628-421c-9038-a4c392f9222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1087f8f4-e5ba-4d40-a147-cdf53bb5bfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4deec883-bb78-48d4-b5d6-c157087fa0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select One</value>
      <webElementGuid>b8279ded-958d-47fb-8b78-462e669df4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One</value>
      <webElementGuid>03992cbb-0313-4c18-92e9-a494c3445dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-main_ddlakomodasi-container&quot;)</value>
      <webElementGuid>1eaff7ef-29d8-4a0e-9878-e34cc7d8a89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-main_ddlakomodasi-container']</value>
      <webElementGuid>ebd35ac6-796d-4054-a61f-d832cedfe1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[8]/div/span/span/span/span</value>
      <webElementGuid>0a227cf8-3e96-4661-93d5-d67a63357633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akomodasi/Hotel per Malam'])[1]/following::span[4]</value>
      <webElementGuid>74271b8e-0195-48aa-ba04-2e7a57f89fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::span[3]</value>
      <webElementGuid>039604d4-fe53-4606-84b0-4a607194fc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp Information'])[1]/preceding::span[4]</value>
      <webElementGuid>728e55c8-cc22-4d18-8041-fcee9f94767f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>f7ccaff1-3ab2-4e90-9148-d714e4b59a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-main_ddlakomodasi-container' and @title = 'Select One' and (text() = 'Select One' or . = 'Select One')]</value>
      <webElementGuid>8f0c10a8-5418-4ea1-b631-b68801b17355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
