<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BBM</name>
   <tag></tag>
   <elementGuidId>ffbe42bb-e694-4b3c-bc6b-56b386b50a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_ddlkm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='main_ddlkm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14560311-b428-4d07-addf-73518d82a86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$ddlkm</value>
      <webElementGuid>821ddea6-71ab-41ad-ba2c-a6e17673d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_ddlkm</value>
      <webElementGuid>7f48732e-a3c8-4aa1-a414-559669bc440e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fde3c564-0a74-4acb-9455-0bae73728d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	- Select One - 
	2000
	1000

</value>
      <webElementGuid>0bdf687f-64ed-4cf7-bba5-3ce25cfef409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_ddlkm&quot;)</value>
      <webElementGuid>95adf28c-ec13-425f-aa7b-65b34fb39f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='main_ddlkm']</value>
      <webElementGuid>8e74e60f-adcf-43fa-b068-e104a63ac4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[3]/div/select</value>
      <webElementGuid>e0748f02-001d-46ed-ae92-126ec587c856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBM/KM'])[1]/following::select[1]</value>
      <webElementGuid>c45e0860-e13c-4c3e-966f-988c75f898ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Biaya'])[1]/following::select[2]</value>
      <webElementGuid>fbcc1321-8e63-4fd8-84c5-3e6ddcd27b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengganti'])[1]/preceding::select[1]</value>
      <webElementGuid>d72709a3-d212-4b17-9beb-d31a11d2069a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jabatan/Grade'])[1]/preceding::select[2]</value>
      <webElementGuid>b90f9377-42d2-402e-b780-9b0163cc7d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>ff5a0bef-08f0-4be7-a289-8945cc39a1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$main$ddlkm' and @id = 'main_ddlkm' and (text() = '
	- Select One - 
	2000
	1000

' or . = '
	- Select One - 
	2000
	1000

')]</value>
      <webElementGuid>cdda3f01-128a-4f6e-ab36-ea45144b497c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
