<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputmgr</name>
   <tag></tag>
   <elementGuidId>8fb246f8-78ca-44d8-b6e6-7c8540bab7b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbmgr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbmgr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fdb1555-18ee-4513-b925-cd7bc0a604c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbmgr</value>
      <webElementGuid>22be39c4-8325-4553-ae18-11015d9592f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>39cceeea-9856-4772-9dea-35f5f495e540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbmgr</value>
      <webElementGuid>697601f0-8541-4856-b5cb-c1c4061c7585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbmgr\',\'\')', 0)</value>
      <webElementGuid>4fee8e96-b1f1-411f-b453-6c3ed85d4ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbmgr&quot;)</value>
      <webElementGuid>d486e1fb-b6a2-47ba-a7a7-10c1ae2a615c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbmgr']</value>
      <webElementGuid>71ba8522-d09b-45f8-92b8-fed68e269f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[4]</value>
      <webElementGuid>8c72f95a-70c1-413a-b56a-ad0b76215774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[4]</value>
      <webElementGuid>6c7207be-6bb5-42ef-87c8-125824ece234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbmgr' and @type = 'checkbox' and @name = 'ctl00$main$cbmgr']</value>
      <webElementGuid>ffd56451-ac0b-4050-9f2e-641a2fb32753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
