<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade_E</name>
   <tag></tag>
   <elementGuidId>6898d0fe-d428-4afb-8309-b25906d0ae3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>201a71c0-37e7-49e1-ac39-50871904e2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbE</value>
      <webElementGuid>fe1ab733-44d1-40cc-8575-16c50d8c11ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d31584a2-d5dc-4b55-ac26-9335eb1adbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbE</value>
      <webElementGuid>c98e77c0-8ab7-452c-a50f-ea0f849d45d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>2e47f356-e770-4ede-8eee-da8410f7be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbE&quot;)</value>
      <webElementGuid>b0832618-7a93-4097-ae90-03b6bb9141ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbE']</value>
      <webElementGuid>17ea1c73-d6ae-471f-bac0-70170f79877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/span[5]/input</value>
      <webElementGuid>626ad536-2c8b-4c5e-86ad-86a85e70f059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input</value>
      <webElementGuid>bca60512-399f-4560-8494-12feb2c6d6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbE' and @type = 'checkbox' and @name = 'ctl00$main$cbE']</value>
      <webElementGuid>d47dace6-9f69-4b6b-95fa-7061d8c66257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
