<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JabatanGrade_semua</name>
   <tag></tag>
   <elementGuidId>966544e1-a19d-4fd2-9ded-a80081ccba92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbsemua']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_cbsemua</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c501d5d4-bb1c-46dc-877b-adb9251ea22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbsemua</value>
      <webElementGuid>51684828-45d8-4b4a-a350-36a4f4f17620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e1c8bebc-aeb3-4a4a-a580-366d0db10177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbsemua</value>
      <webElementGuid>96fe8448-e8a8-41f6-b611-af6f2a699641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbsemua\',\'\')', 0)</value>
      <webElementGuid>d038b106-8f64-4d3b-80ae-fc581e32a904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbsemua&quot;)</value>
      <webElementGuid>40136dd2-0c5a-4a54-a7f3-6a4d401f68b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbsemua']</value>
      <webElementGuid>e9aa0156-dbba-4c2d-9dd0-c8983ebbe75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input</value>
      <webElementGuid>251ddc07-15ee-4f7d-8ea5-df17ae405202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>871434d4-5e43-499c-8521-854387072024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbsemua' and @type = 'checkbox' and @name = 'ctl00$main$cbsemua']</value>
      <webElementGuid>c47e08b7-1db6-49d8-b10d-3e3f2d811376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
