<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_srmgr</name>
   <tag></tag>
   <elementGuidId>809316e1-08cd-48a9-9d3f-74180d1ba537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbsm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_cbsm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67ab7e17-73c3-4368-ab0b-e1c18ef9cabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbsm</value>
      <webElementGuid>a282cd46-6468-4307-9281-a84d6acb3161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3fbf9fd6-4fa5-4173-8231-da977e629563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbsm</value>
      <webElementGuid>ed5ebdb3-468e-4679-9330-8cf095dde22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbsm\',\'\')', 0)</value>
      <webElementGuid>dd200da3-da09-424b-b607-c13eeb04c8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbsm&quot;)</value>
      <webElementGuid>1f02e22f-16c1-47f2-8a27-129e54fb23d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbsm']</value>
      <webElementGuid>d01debe0-4ea6-4ed5-abd6-e34809c34ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[3]</value>
      <webElementGuid>98e87d53-c526-4df5-880f-788358fa124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[3]</value>
      <webElementGuid>9c5c1845-467b-43ca-b9bf-72ede2f87e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbsm' and @type = 'checkbox' and @name = 'ctl00$main$cbsm']</value>
      <webElementGuid>dfb4e4ba-566e-490c-b10f-3f6383d7fff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
