<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lama Perdin_12</name>
   <tag></tag>
   <elementGuidId>abe8db82-8938-4e46-9162-34c863719482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbllama_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbllama_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f325f4d-00fd-4179-a020-51ae65390d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbllama_2</value>
      <webElementGuid>bb32717d-9083-4623-ad00-cb7cc2405272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2ed22a45-8cf0-4eff-97c8-dedf60651354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbllama$2</value>
      <webElementGuid>78ed77e0-06f2-4a5b-93ad-17903263c415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>&lt; 12</value>
      <webElementGuid>09232afb-1719-4c24-8a73-3ae0aa2c033c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbllama_2&quot;)</value>
      <webElementGuid>86152c0b-b40c-4d3c-a337-e19e994dcdab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbllama_2']</value>
      <webElementGuid>e56e1939-9933-4e0c-a5ff-a974ea5bb2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_cbllama']/tbody/tr[3]/td/input</value>
      <webElementGuid>8bd997ec-0c05-44e1-a7d1-e7faff814c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>bc365d85-66ab-4c9a-b013-88b46c980d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbllama_2' and @type = 'checkbox' and @name = 'ctl00$main$cbllama$2']</value>
      <webElementGuid>b2c5a27b-3d69-462d-b7fd-bec87f95c451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
