<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ofc</name>
   <tag></tag>
   <elementGuidId>1740ccd4-3c2e-49f3-ba08-5780043c806a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbofc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbofc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85ecb9a2-d05d-48da-9b13-e0c6c9c4f04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbofc</value>
      <webElementGuid>b54436be-de67-4f9c-a08f-42a751a5146d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f291c7f5-90d0-4c91-aa7f-cd821ed78fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbofc</value>
      <webElementGuid>f7d99696-ed27-4587-81c3-62937221369a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbofc\',\'\')', 0)</value>
      <webElementGuid>795f7d32-b203-48f3-bb62-382aca29300a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbofc&quot;)</value>
      <webElementGuid>25a51b20-b0e3-4345-b613-2b5c154ff4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbofc']</value>
      <webElementGuid>24cf5c10-1ae6-4c4e-8f1d-42de9d280402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[7]</value>
      <webElementGuid>95a58fe5-06a8-422b-90d7-d97206bd9cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[7]</value>
      <webElementGuid>0480e198-b6f2-4142-9b96-0d21efa5e0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbofc' and @type = 'checkbox' and @name = 'ctl00$main$cbofc']</value>
      <webElementGuid>5ae9b2e5-b1b7-4c4f-b033-23a9f11449a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
