<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_staff</name>
   <tag></tag>
   <elementGuidId>93036a48-27aa-4494-8831-20ee5da8b5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbstaff</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbstaff']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cff15f41-5759-43bb-8bcb-1be1b076ece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbstaff</value>
      <webElementGuid>e3932e91-8744-4403-beba-364b5fa9f935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>36eece5a-7d33-494e-9a91-cdb753d014f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbstaff</value>
      <webElementGuid>b5e93c27-8d70-4d1e-9870-014eb9a06409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbstaff\',\'\')', 0)</value>
      <webElementGuid>37abc123-cbaf-40d3-ad27-e7d2e0abf5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbstaff&quot;)</value>
      <webElementGuid>33d9960a-590b-4381-8b07-5d33da5fb5a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbstaff']</value>
      <webElementGuid>7f69e4df-cda2-4598-bc9c-ef6507e19b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[8]</value>
      <webElementGuid>9098a2f4-4300-4057-8f18-d4d4b9a9b4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>18b5fd5c-d8d8-4bae-8efc-fb936bb48b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbstaff' and @type = 'checkbox' and @name = 'ctl00$main$cbstaff']</value>
      <webElementGuid>96b8c867-3b92-4953-bc19-ee4998583b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
