<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nonstaff</name>
   <tag></tag>
   <elementGuidId>56b2e473-6692-47a4-8135-2ee1d785e2d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbnon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbnon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6402f77a-f172-4e0e-b4f9-033122df9b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbnon</value>
      <webElementGuid>0feb7193-4a99-4303-9d01-ba3cc242abc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a2084431-4419-4de8-8b50-bf052053faee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbnon</value>
      <webElementGuid>da9f0a83-904c-4245-a96f-ac51441eabf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbnon\',\'\')', 0)</value>
      <webElementGuid>0e50eb5a-bb5a-4260-acef-1771b9a83c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbnon&quot;)</value>
      <webElementGuid>27c3d5c0-7eff-41d0-b67f-9a067ac0446b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbnon']</value>
      <webElementGuid>393c363e-8319-4220-8720-c80c30821d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[9]</value>
      <webElementGuid>6feca186-25c1-4ad6-987b-a7531c994049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>5f097641-f327-4618-b614-b3dd23b49a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbnon' and @type = 'checkbox' and @name = 'ctl00$main$cbnon']</value>
      <webElementGuid>a73b5e78-b618-4ff4-90de-a19eca48c306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
