<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_spv</name>
   <tag></tag>
   <elementGuidId>1ee03659-2b5c-472c-89d0-c86e26603d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbspv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbspv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>670432d6-513a-40b5-9ec1-4ec49468b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbspv</value>
      <webElementGuid>d98f5a39-f543-427a-b094-1b35538bb7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>29d35af2-8f94-4097-8ab3-691d859af482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbspv</value>
      <webElementGuid>b17c7481-4d4a-49dc-820f-58942999ae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbspv\',\'\')', 0)</value>
      <webElementGuid>58aafc41-3860-4d42-bc3a-21720c62fabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbspv&quot;)</value>
      <webElementGuid>247477fd-2a08-40ea-a3e4-83a29bad5df3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbspv']</value>
      <webElementGuid>93614b45-8828-48d4-a94d-431c84e7b668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[5]</value>
      <webElementGuid>32a73ab9-6dbd-4958-9981-0b9286173f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[5]</value>
      <webElementGuid>d57eb55a-0e67-43c6-96c1-66191f993f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbspv' and @type = 'checkbox' and @name = 'ctl00$main$cbspv']</value>
      <webElementGuid>2aedd5c0-8a20-47f2-b85d-d8e21a30ba91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
