<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade_A</name>
   <tag></tag>
   <elementGuidId>452dfe2d-6e3a-479e-8dac-4f9a9da2eed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'main_cbsm' and @type = 'checkbox' and @name = 'ctl00$main$cbsm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_cbsm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbsm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>083173a6-6406-48eb-87d1-7a18aad80c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbsm</value>
      <webElementGuid>d517697f-cf93-495e-b9a5-67fadff99707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b76a53b9-beda-4b25-b6bd-01eaca7265e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbsm</value>
      <webElementGuid>dde3a2a8-1a3a-4814-bb3b-0862ea5bf6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbsm\',\'\')', 0)</value>
      <webElementGuid>441f6f94-383e-4b46-9370-98882983b45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbsm&quot;)</value>
      <webElementGuid>9d05ee49-9c3b-462e-adb2-d73ebf427721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbsm']</value>
      <webElementGuid>b642e754-3f0a-4ba6-a89f-15b80a4344eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[3]</value>
      <webElementGuid>fb1a6b9a-c100-4807-ab80-ea9800078b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[3]</value>
      <webElementGuid>013aa4d9-59d7-4422-9cef-9bdfa43d9467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbsm' and @type = 'checkbox' and @name = 'ctl00$main$cbsm']</value>
      <webElementGuid>fe87653d-d49d-4f6d-88ed-6cd1b313ce9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
