<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lama Perdin_16</name>
   <tag></tag>
   <elementGuidId>3d7d94f5-9dca-4bc4-ae0a-cd1c61c17fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbllama_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbllama_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c7638d4-89f2-4f0e-928a-0c58b65e266c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbllama_0</value>
      <webElementGuid>ac56812f-5cb0-4eda-9ee9-69f4679402a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>abe55a37-3dc5-424b-a4c1-1fca23c6e8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbllama$0</value>
      <webElementGuid>b5a15b8e-8be0-4989-be76-9078a88a6e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>> 16</value>
      <webElementGuid>6a2c77b8-6909-401e-963f-409e2f83c020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbllama_0&quot;)</value>
      <webElementGuid>5e54c71d-8651-4bec-be2d-2744ed629536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbllama_0']</value>
      <webElementGuid>ddbbb3d3-9d32-43fb-aabf-6d104af89d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_cbllama']/tbody/tr/td/input</value>
      <webElementGuid>12327cdf-6f4c-4d82-9aa3-0c378cc89a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>1ac35129-5686-40b0-ad84-6172fdea851e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbllama_0' and @type = 'checkbox' and @name = 'ctl00$main$cbllama$0']</value>
      <webElementGuid>bef64d99-7dc5-4602-aa18-f735775af18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
