<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade_A</name>
   <tag></tag>
   <elementGuidId>452dfe2d-6e3a-479e-8dac-4f9a9da2eed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbsm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbsm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e415d606-bd07-4e70-abc8-39b29920e329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbsm</value>
      <webElementGuid>d7135b88-e1df-4f00-bf66-4304faf52bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c205d11-9409-44c7-a901-1278c312c2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbsm</value>
      <webElementGuid>eed7b177-d38b-483e-a3ec-b8c4573746af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$main$cbsm\',\'\')', 0)</value>
      <webElementGuid>f59e0178-9605-4370-aefa-3bcd50981892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbsm&quot;)</value>
      <webElementGuid>f45a9607-7750-474c-8679-f196f6bd86ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbsm']</value>
      <webElementGuid>0dc18d97-577d-4804-b2aa-3ea3af848d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/input[3]</value>
      <webElementGuid>40e56558-48c0-489f-9166-1aba2256e854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[3]</value>
      <webElementGuid>86a4ec51-b5ab-4236-ac7a-3a8318b9ffb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbsm' and @type = 'checkbox' and @name = 'ctl00$main$cbsm']</value>
      <webElementGuid>daeda38e-59f7-40b6-8182-e404574073d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
