<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade_G</name>
   <tag></tag>
   <elementGuidId>ce7436c5-feb8-46b0-b154-3892c3a68f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e73ff010-aa90-4136-ae3e-39eb980d2d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbG</value>
      <webElementGuid>97d55cb9-e23a-46e2-9623-ce48728f619e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c329753-5595-4573-84c5-3b8691070558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbG</value>
      <webElementGuid>b00cae32-66f2-4dbd-a3e6-2538039f7800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>43595424-18a5-4ec1-b4c0-0bffc5986254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbG&quot;)</value>
      <webElementGuid>d08d6c2d-e423-438f-bb13-61c97bbc651d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbG']</value>
      <webElementGuid>3308fba0-54c3-4172-9026-5cbf44d46c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/span[7]/input</value>
      <webElementGuid>1480f604-45bf-4f69-aa72-c70f9dea3bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/input</value>
      <webElementGuid>3c9650b4-d663-49ee-90e9-ecb1f6407793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbG' and @type = 'checkbox' and @name = 'ctl00$main$cbG']</value>
      <webElementGuid>cac9abbe-23c4-4d55-8fc0-cb3e07fa4375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
