<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lama Perdin_12_16</name>
   <tag></tag>
   <elementGuidId>b2615986-5cea-48ed-8883-5b5c4d99abef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbllama_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbllama_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff5c6140-dc56-4d8d-b0ad-e37a40581bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbllama_1</value>
      <webElementGuid>63d0a166-c2d3-4f54-a307-3a79feb298e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5798c355-4bdb-40ee-b259-44dd19fdb06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbllama$1</value>
      <webElementGuid>1b9e78d9-4b7d-433e-957f-a0ad2d9b720f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>>= 12 &lt;= 16</value>
      <webElementGuid>010197fe-4042-4448-a8e9-16d05d1dc5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbllama_1&quot;)</value>
      <webElementGuid>c207a32c-db4f-437a-82cc-d54357852ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbllama_1']</value>
      <webElementGuid>88a54661-8211-4c5b-8cc1-c29227921676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_cbllama']/tbody/tr[2]/td/input</value>
      <webElementGuid>dbe70f87-fffc-4fd9-9fd0-b447a28bb2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>e94cd60b-5ca6-4901-bf22-54eea2307380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbllama_1' and @type = 'checkbox' and @name = 'ctl00$main$cbllama$1']</value>
      <webElementGuid>6828a7f7-060b-45bf-aef3-c41d5b258bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
