<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade_B</name>
   <tag></tag>
   <elementGuidId>9835013b-b11a-40bc-80c8-bc733d59e665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_cbB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_cbB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>764ad0c4-d6de-4ca7-8918-89ec46fa54e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_cbB</value>
      <webElementGuid>5f37d2be-9c4e-403a-a3c6-cfaa84e879ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>754d55ac-dd70-49fe-b1ae-07c78509cb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$cbB</value>
      <webElementGuid>87d018ce-dded-4290-887c-6b9dc5f9da43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>98fd850f-1a40-4a3f-9a76-6ee839596694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_cbB&quot;)</value>
      <webElementGuid>75a2a569-667e-4341-b254-433bbe08cfe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_cbB']</value>
      <webElementGuid>61462c7c-71ad-4699-9a9d-2fb9a9e5af2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[5]/div/span[2]/input</value>
      <webElementGuid>00986a2b-2630-40c1-9a62-871a05fa16e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>c565f7f3-924b-4317-92e4-8fa6c390e9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'main_cbB' and @type = 'checkbox' and @name = 'ctl00$main$cbB']</value>
      <webElementGuid>504e2b3e-f6e4-403a-983b-d56a83413eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
