<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JenisPerjalanan-LuarKota</name>
   <tag></tag>
   <elementGuidId>590770c3-2b1e-4ab4-9073-b7f1a4945d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Luar Kota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c63ea4ee-a2d6-4497-a29f-1848374481c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709193088458</value>
      <webElementGuid>5b47d0d1-dd54-44c1-af12-e51a6ae0e9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[value='Luar Kota']</value>
      <webElementGuid>92a526ff-7ccc-49b5-98b0-0fcb49c90348</webElementGuid>
   </webElementProperties>
</WebElementEntity>
