<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JenisPerjalanan-DalamKota</name>
   <tag></tag>
   <elementGuidId>20447682-42e5-4de8-aac2-28fa102b72c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[.='Dalam Kota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ffda16d5-38a9-47a6-890f-e518b9b1517e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1709193102859</value>
      <webElementGuid>38e92878-807d-40b3-867f-86eaeb7df768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[value='Dalam Kota']</value>
      <webElementGuid>dd9892f6-f644-4daf-ab7e-b532acef12a9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
