<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1000000.00</name>
   <tag></tag>
   <elementGuidId>cd1b939f-86f1-42f0-a1c2-d338c8ed5b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'select2-results__option select2-results__option--highlighted']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9d46b3cc-2555-4a7c-a989-bfff516f5a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>a2f9d185-7942-4ea9-954b-bd8d058396af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-main_ddlakomodasi-result-75xl-1000000.00</value>
      <webElementGuid>f2e59b6d-d070-4e11-8626-80e39c6bdb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a8fad845-6828-4952-9cdb-393a5a76fd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5f259c1-d3bb-46e6-a239-4a611850bc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-main_ddlakomodasi-result-75xl-1000000.00</value>
      <webElementGuid>bbfe6936-e3cf-40d7-aaa9-954d580d185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1000000.00</value>
      <webElementGuid>ded931e4-0174-49f4-a954-9889cb52335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-main_ddlakomodasi-result-75xl-1000000.00&quot;)</value>
      <webElementGuid>5e4068fa-5498-466a-989a-c34977446b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-main_ddlakomodasi-result-75xl-1000000.00']</value>
      <webElementGuid>1f19b97e-c397-43c5-819a-8d7e2edc04e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-main_ddlakomodasi-results']/li</value>
      <webElementGuid>d5f4cbe1-8e48-44fa-ad5c-8a723d9b6511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>1714d97d-cd51-4fd2-81d1-4841eacd3bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>8a64a7b6-b6d5-4457-a2a4-7f498fea90a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-main_ddlakomodasi-result-75xl-1000000.00' and (text() = '1000000.00' or . = '1000000.00')]</value>
      <webElementGuid>e089f91e-9cb4-4fce-9947-a905b05176c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
