<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uang Makan</name>
   <tag></tag>
   <elementGuidId>778cce47-44bc-48b5-8876-76d7e4972021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_ddluangmakan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='main_ddluangmakan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aec6ea9a-595d-4eec-83f2-5f68881e8988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$ddluangmakan</value>
      <webElementGuid>adebcdeb-df08-4af7-9c98-25ad25960393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_ddluangmakan</value>
      <webElementGuid>e2c58f51-576b-4fee-8fd7-b40af896dade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>60a7636c-8455-41a4-bcfe-7e7b75d6d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	- Select One -
	100%
	75%
	0

</value>
      <webElementGuid>179608c9-029b-4523-8900-89fe2f1ad5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_ddluangmakan&quot;)</value>
      <webElementGuid>6ded1fa2-fc2f-4693-a629-0f49b3e7c628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='main_ddluangmakan']</value>
      <webElementGuid>8580bb5d-7cfc-4241-9071-4d13a8b1167b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div[3]/div/section[2]/div/div[2]/div[2]/div/div[7]/div/select</value>
      <webElementGuid>75238ed9-5e93-4268-8b00-52c7805a0fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uang Makan'])[2]/following::select[1]</value>
      <webElementGuid>07a6688c-afba-49e2-ae22-4a7ec58412fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>62a56478-ff6b-49c2-9cd1-3463a36e7eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whatsapp Information'])[1]/preceding::select[2]</value>
      <webElementGuid>e1bf06d1-42d3-4186-a038-7e956e4d1612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>4948d7f6-ae01-4853-af3d-140f13b9a379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$main$ddluangmakan' and @id = 'main_ddluangmakan' and (text() = '
	- Select One -
	100%
	75%
	0

' or . = '
	- Select One -
	100%
	75%
	0

')]</value>
      <webElementGuid>b05919da-9fa4-4d3f-a1b6-190f3f5c4a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
