<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uang Makan-75</name>
   <tag></tag>
   <elementGuidId>2efa6218-d455-4e7d-a61d-a4a16ff81bc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[value='75%']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[.='75%']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[value='75%']</value>
      <webElementGuid>ffe9f490-6894-4772-bb71-87e4df0a7673</webElementGuid>
   </webElementProperties>
</WebElementEntity>
