<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan Perdin</name>
   <tag></tag>
   <elementGuidId>0192e4b9-7d0b-4d98-8a4b-400fef78b6b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f535da38-f68a-46fc-a712-1f7f502156a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_5 TreeView1_7</value>
      <webElementGuid>d14a72f3-35c5-46ce-8133-46605faabe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$TreeView1','s5303')</value>
      <webElementGuid>bc4ede56-0826-4220-8a5c-030996c40c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TreeView_SelectNode(TreeView1_Data, this,'TreeView1t1');</value>
      <webElementGuid>d5dbd87e-2514-4e7c-afc3-0f2f128fbb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t1</value>
      <webElementGuid>c050f044-9cfd-45d7-8396-47f1990073ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan Perdin</value>
      <webElementGuid>b91db146-30ee-4d50-bc60-fd49d6e7010d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t1&quot;)</value>
      <webElementGuid>8c3f6697-b5d6-435f-b1f0-c984bb7e1b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t1']</value>
      <webElementGuid>09061462-b944-4bc8-ae0a-da6bb7b37a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1']/table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>1d3e39c4-aaa8-4496-896a-98eca4935da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pengajuan Perdin')]</value>
      <webElementGuid>0f208684-157a-489b-badd-7f1981621eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Biaya'])[1]/following::a[2]</value>
      <webElementGuid>0b6b744b-2ecc-40b8-a54e-03feac9043ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links.'])[1]/following::a[3]</value>
      <webElementGuid>c309a054-409b-499b-95bb-dc0d60ec0854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan'])[1]/preceding::a[1]</value>
      <webElementGuid>3fee4698-8f48-44d4-bbb5-f4a108ab00c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Realisasi'])[1]/preceding::a[2]</value>
      <webElementGuid>3103d60d-c491-4370-acc0-c0a39a339ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengajuan Perdin']/parent::*</value>
      <webElementGuid>a65d2768-c86f-41fd-b257-bd33f9a323d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$TreeView1','s5303')&quot;)]</value>
      <webElementGuid>7c963e88-775c-4339-9262-80a94aeab197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>28485aa8-0e99-463e-8cb8-1113e7fdabd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$TreeView1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;s5303&quot; , &quot;'&quot; , &quot;)&quot;) and @id = 'TreeView1t1' and (text() = 'Pengajuan Perdin' or . = 'Pengajuan Perdin')]</value>
      <webElementGuid>12d6c0b0-4358-47e8-b135-d066b248de50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
