<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan</name>
   <tag></tag>
   <elementGuidId>28475c5b-fa0e-4e20-ac62-1579706a20c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TreeView1t2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1t2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f73ec736-3ab3-4d42-87f4-f454786fcabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_0 TreeView1_1 TreeView1_7</value>
      <webElementGuid>e83c0ae0-ff73-46e4-843a-a243eff1e016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Apps/PerjalananDinas/PengajuanPerDin.aspx</value>
      <webElementGuid>dbe74520-c765-4578-8dcb-4cf3bc072643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TreeView1t2</value>
      <webElementGuid>cc7f7761-eb1c-471e-b26d-e51453bca7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan</value>
      <webElementGuid>82373e76-8556-46c2-922b-8b68621cb369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1t2&quot;)</value>
      <webElementGuid>8a3c8db5-d702-44a6-b6d4-4d032be9146d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='TreeView1t2']</value>
      <webElementGuid>9d1ad089-8671-40c3-9f70-b6db115a173b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n1Nodes']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>ec0694f0-cd2b-46e7-967b-4c2410644642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pengajuan')])[2]</value>
      <webElementGuid>2c8003f2-c86a-4680-a6fb-4706bc6c2312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Perdin'])[1]/following::a[1]</value>
      <webElementGuid>bb9c57fd-a783-419c-80ff-ba16b8fc6706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Biaya'])[1]/following::a[3]</value>
      <webElementGuid>0bfbe058-974e-46c1-a204-6f921a646e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Realisasi'])[1]/preceding::a[1]</value>
      <webElementGuid>408003a2-afe6-4614-9c11-c2410e29608d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemesanan Tiket'])[1]/preceding::a[3]</value>
      <webElementGuid>bc51c8bd-1e6b-4dd6-895b-603b0a3b7bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengajuan']/parent::*</value>
      <webElementGuid>d36c1203-4157-4535-9ada-c9411eea9422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Apps/PerjalananDinas/PengajuanPerDin.aspx')]</value>
      <webElementGuid>0351c341-3dc5-4f0b-a79d-9734d5647b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>4265dd30-9fa5-49fa-820f-cef87424bcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Apps/PerjalananDinas/PengajuanPerDin.aspx' and @id = 'TreeView1t2' and (text() = 'Pengajuan' or . = 'Pengajuan')]</value>
      <webElementGuid>a5cffed0-f93f-49d2-b447-37784fefeda1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
